gather_interval_seconds: 300
org: 'calyx'
bucket: 'network'
user: 'unknown'
location: 'unknown'
device: 'unknown'

iperf3_duration_seconds: 4
iperf3_cmd: '/usr/bin/iperf3'
iperf3_host: 'speedtest.calyx.dev'
iperf3_port: '5201'

ooni_cmd: '/usr/local/bin/miniooni-linux-amd64'

# this is the time limit for tests using fast.com
netflix_run_seconds: 4

influxdb_host: 'http://185.220.103.39:8086'
influxdb_token: 'awlC8h2nY124E8joIdTUbRaATI4B00ldPIV7QRLfmdJonk5WPYu72IoOML01HPCqFijRwTjDzwrw5oKvLg7v5A=='

measurements:
#- iperf3
 - ooni.dash
 - ooni.ndt
 - netflix
# - mifi

pause_between_measurements: 5
debug: false
