gather_interval_seconds: 300
org: 'calyx'
bucket: 'network'
user: 'unknown'
location: 'unknown'
device: 'unknown'

allowed_devices:
 - mifi-m2000
 - franklin-t10
 - quanta-5g
 - mifi-x

iperf3_duration_seconds: 4
iperf3_cmd: '/usr/bin/iperf3'
iperf3_host: 'speedtest.calyx.dev'
iperf3_port: '5201'

ooni_cmd: '/usr/local/bin/miniooni-linux-amd64'

# this is the time limit for tests using fast.com
netflix_run_seconds: 4

influxdb_host: 'https://xn--3s8hu2f.calyx.dev'
influxdb_token: 'hZR_dRwxok01Y5DCN3Qd3wplW5DFDCfpEAmZkQEnG3rcyVMrEQSMQHArfBUzfd-Ml01mONV4W__JI2xtyFqdaw=='

measurements:
#- iperf3
 - ooni.dash
 - ooni.ndt
 - netflix
# - mifi

pause_between_measurements: 5
debug: false
