gather_interval_seconds: 300
org: 'calyx'
bucket: 'netsloth'
user: 'unknown'
location: 'unknown'
device: 'unknown'

allowed_devices:
 - mifi-m2000
 - franklin-t10
 - quanta-5g
 - mifi-x
 - office-wifi
 - jextream


iperf3_cmd: '/usr/bin/iperf3'
iperf3_port: '5201'
iperf3_duration_seconds: 4
iperf3_host: 'speedtest.calyx.dev'

ooni_cmd: '/usr/local/bin/miniooni'

# this is the time limit for tests using fast.com
netflix_run_seconds: 12

# https://💻🦥.calyx.dev
influxdb_host: 'https://xn--3s8hu2f.calyx.dev'
influxdb_token: 'uKFm6ruunaJUg1fUqBr5-TBzm1s4wl-GSxngFY1q1Xd8ddy3N5XozB01ECIQVsdjp-XMqf6XRkg9_R2vYSQVFQ=='

measurements:
 - iperf3?iperf3_host=iperf.webdev1.calyx.dev
 - ooni.dash
 - ooni.ndt
 - netflix
# - mifi

pause_between_measurements: 5
debug: false
